name: fraction_example
description: A Dart CLI application that uses the API of the 'fraction' package.
version: 1.0.9
repository: https://github.com/albertodev01/fraction/tree/master/example
homepage: https://pub.dev/packages/fraction
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  fraction:
    path: ../

dev_dependencies:
  test: ^1.25.15
