name: fraction_example
description: A Dart CLI application that uses the API of the 'fraction' package.
version: 1.0.6
repository: https://github.com/albertodev01/fraction/tree/master/example
homepage: https://fluttercompletereference.com/
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  fraction:
    path: ../

dev_dependencies:
  dart_code_metrics: ^5.7.3
  test: ^1.24.2
