name: fraction_example
description: A simple Dart CLI application for the 'fraction' package
version: 1.0.5
repository: https://github.com/albertodev01/fraction/tree/master/example
homepage: https://fluttercompletereference.com/
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  fraction:
    path: ../

dev_dependencies:
  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.17.1

  # https://pub.dev/packages/test
  test: ^1.21.4
