name: fraction
description: A package that helps you work with fractions and mixed fractions.
version: 5.0.0
repository: https://github.com/albertodev01/fraction
homepage: https://fluttercompletereference.com/

environment:
  sdk: ^3.0.0

dev_dependencies:
  dart_code_metrics: ^5.7.3
  test: ^1.24.2
