name: fraction
description: A package that helps you dealing with mathematical fractions. Work with fractions, mixed fractions and types conversions.
version: 1.2.1
repository: https://github.com/albertodev01/fraction
homepage: https://fluttercompletereference.com/

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.14.6