name: fraction
description: A package that helps you working with mathematical fractions.
version: 4.1.1
repository: https://github.com/albertodev01/fraction
homepage: https://fluttercompletereference.com/

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.15.2

  # https://pub.dev/packages/test
  test: ^1.21.1
