name: fraction
description: A package that helps you working with fractions and mixed fractions.
version: 4.1.4
repository: https://github.com/albertodev01/fraction
homepage: https://fluttercompletereference.com/

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.17.1

  # https://pub.dev/packages/test
  test: ^1.21.5
