name: fraction
description: A package that helps you working with mathematical fractions.
version: 4.0.1
repository: https://github.com/albertodev01/fraction
homepage: https://fluttercompletereference.com/

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  # https://pub.dev/packages/coverage
  coverage: ^1.1.0

  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.10.1

  # https://pub.dev/packages/lints
  lints: ^1.0.1

  # https://pub.dev/packages/test
  test: ^1.20.1
