name: fraction
description: A package that helps you dealing with mathematical fractions. Work with fractions, mixed fractions and types conversions.
version: 3.0.1
repository: https://github.com/albertodev01/fraction
homepage: https://fluttercompletereference.com/

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  coverage: ^1.0.2
  test: ^1.16.8