name: fraction
description: A package that helps you dealing with mathematical fractions. Work with fractions, mixed fractions and types conversions.
version: 3.1.0
repository: https://github.com/albertodev01/fraction
homepage: https://fluttercompletereference.com/

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  # https://pub.dev/packages/coverage
  coverage: ^1.0.3

  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.2.1

  # https://pub.dev/packages/lints
  lints: ^1.0.1

  # https://pub.dev/packages/test
  test: ^1.17.12