name: fraction
description: A package that helps you work with fractions and mixed fractions.
version: 5.0.1
repository: https://github.com/albertodev01/fraction
homepage: https://fluttercompletereference.com/

environment:
  sdk: ^3.0.0

dev_dependencies:
  test: ^1.24.4
