name: fraction
description: A package that helps you work with fractions and mixed fractions.
version: 5.0.3
repository: https://github.com/albertodev01/fraction
homepage: https://pub.dev/packages/fraction

environment:
  sdk: ^3.4.0

dev_dependencies:
  test: ^1.25.8
