name: fractions_ci

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
      - develop
      
jobs:
  verify_fraction_package:
    name: fraction pub package
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
        
      - name: Format
        run: dart format --set-exit-if-changed .
        
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings
        
      - name: Run tests
        run: dart pub global activate coverage && dart pub global run coverage:test_with_coverage
        
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v3
        with:
          min_coverage: 100

  verify_fraction_example:
    name: fraction package - Dart example app
    needs: [verify_fraction_package]
    runs-on: macos-latest
    defaults:
      run:
        working-directory: example
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
        
      - name: Format
        run: dart format --set-exit-if-changed .
        
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings
        
      - name: Run tests
        run: dart test 
